[project]
name = "pydantic-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.14.1",
    "pydantic[email]>=2.10.4",
]
[tool.mypy]
strict = "True"
plugins =  [
    "pydantic.mypy"
]
